# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest' # try out

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Installing .NET Core SDK 3.1.x'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- script: dotnet build --configuration $(buildConfiguration) BlazorChatSample.sln
  displayName: 'Building $(buildConfiguration)...'

- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --framework netcoreapp3.1 --self-contained true --runtime win-x86 BlazorChatSample.Server\BlazorChatSample.Server.csproj
  displayName: 'Publishing $(buildConfiguration)...'
  
- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'
