# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK for Preview7...'
  inputs:
    version: 3.0.100-preview8-013656

- script: dotnet build --configuration $(buildConfiguration) BlazorChatSample.sln
  displayName: 'Building $(buildConfiguration)...'

- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --framework netcoreapp3.0 --self-contained true --runtime win-x86 BlazorChatSample.Server\BlazorChatSample.Server.csproj
  displayName: 'Publishing $(buildConfiguration)...'
  
# - task: DotNetCoreCLI@2
#   displayName: 'Publishing App...'
#   inputs:
#     command: publish 
#     projects: BlazorChatSample.Server\BlazorChatSample.Server.csproj
#     arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#     zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'
